force-app/main/default/objects/Case/fields/Nonconformance__c.field-meta.xml
<CustomField>
    <fullName>Nonconformance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nonconformance</label>
    <referenceTo>SQX_Nonconformance__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SQX_Nonconformance__c/SQX_Nonconformance__c.object-meta.xml
<CustomObject>
    <label>Nonconformance</label>
    <nameField>
        <displayFormat>NC - {0000000000}</displayFormat>
        <label>Nonconformance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nonconformances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_CaseTrigger.cls
@isTest
public class Test_CaseTrigger {
    @testSetup
    public static void testCaseInsertion() {
        
        Case testCase = new Case();
        testCase.Subject = 'Test Case';
        testCase.Description = 'Test Desc';
        testCase.Type = 'Problem';
        
        Case testCaseII = new Case();
        testCaseII.Subject = 'Test Case2';
        testCaseII.Description = 'Test Desc2';
        testCaseII.Type = 'Other';
        
        //Test.startTest();
        insert testCase;
        insert testCaseII;
        testCaseII.Type = 'Problem';
        update testCaseII;
        //Test.stopTest();
        
    }
    
    @isTest
    public static void testmeathod(){
        List<Case> caseList = [SELECT Id , Description , Subject, type, Nonconformance__c, Nonconformance__r.QMS_Reference_Number__c, CaseNumber from Case WHERE Type = 'Electrical'];
        Test.startTest();
        for(Case cs : caseList){
            if(cs.Type == 'Problem'){
                system.assertEquals(cs.Nonconformance__r.QMS_Reference_Number__c, cs.CaseNumber);
            }
        }
        Test.stopTest();
    }
}